Fine grained kill signals on unix
ClementTsang/bottom pull request #263
Opened 2020-10-02 20:27 UTC by LlinksRechts

## Description

This PR adds a menu for selecting the signal to send to the selected process when pressing `dd` in unix.

![image](https://user-images.githubusercontent.com/10536802/94966233-33f71580-04fd-11eb-8831-d6e119c02827.png)

The signals are aligned in a 8×8 grid, which can be navigated with either the arrow keys, `hjkl`, or the mouse (if enabled). In addition, number keys can be pressed to quickly jump to the respective signal. On enter, the selected signal is sent to the process and the popup is closed (or no signal is sent if `0: Cancel` is selected).

The signal selected by default is 15 (SIGTERM), which is the default signal for killing processes on unix systems.

## Issue

Closes: #251 

## Type of change

- [x] _New feature (non-breaking change which adds functionality)_

## Test methodology

Tested on:  
- [ ] _Windows_
- [ ] _macOS_
- [x] _Linux_

The feature was tested on Linux. In theory, the original functionality should still be in place for windows builds; however, I was not able to verify this as I could not get the app to run properly on windows in any version (including current master, release branch). I can verify that the build succeeds and the app starts on windows, but the output I get in the terminal (cmd, powershell, git bash) of my (virtual) machine (win7) is garbled, and I sadly don't have any other versions of windows to test with (according to the documentation of crossterm, it should work on win7...).

## Checklist

- [x] _Change has been tested to work, and does not cause new breakage unless intended_
- [x] _Code has been self-reviewed_
- [x] _Passes Travis tests (clippy check and `cargo test` check)_
- [x] _Areas your change affects have been linted using rustfmt (`cargo fmt`)_
- [x] _No merge conflicts arise from the change_

2020-10-03 02:31 UTC, ClementTsang commented
Firstly, thanks for the PR - I appreciate it a lot, especially since I'm kinda swamped with working on a lot of other stuff rn.

I'll take a closer look at the implementation parts and leave any suggestions if necessary in a bit, but one thing I may want to change is how the values are laid out.  Since the strings themselves are quite long, it kinda looks a bit weird to me at least when I use it in a vertical terminal (which I normally use):
![image](https://user-images.githubusercontent.com/34804052/94981185-10809a80-04fe-11eb-9fa4-b94065256b7e.png)

The nature of the layout also doesn't really handle window size changes too well either
![image](https://user-images.githubusercontent.com/34804052/94981225-5ccbda80-04fe-11eb-92ef-b5bffd03a6a7.png)

Not sure how to exactly change it, but maybe going for a scrollable list would work better?  I'm open to any ideas.

2020-10-03 02:33 UTC, ClementTsang commented
Oh, right, and I'll test it on other platforms as well (macOS and Windows) later.

2020-10-03 13:22 UTC, LlinksRechts commented
the thing with the layout is a good point; i have to admit that i havent tried resizing...  
i'll see if i can find a better solution, and of course i'm open to suggestions (since I usually have my terminal open on my 4k monitor, i probably have another perspective on the problem...)

2020-10-03 18:51 UTC, LlinksRechts commented
I have replaced the grid with a scrollable list; what do you think? Imo it looks pretty usable... (and also scales better)

![image](https://user-images.githubusercontent.com/10536802/94999481-f60bf700-05b9-11eb-9ce0-62df78660ed2.png)

I'm not completely satisfied with the code yet, so I havent added it to the PR, but you can see it on the `kill-list-scrollable` in my fork

Also, I havent tried building on windows yet, so I might have broken smth

2020-10-04 02:26 UTC, ClementTsang requested changes

2020-10-04 02:30 UTC, ClementTsang commented
Also yeah feel free to take your time on this.

2020-10-04 18:25 UTC, LlinksRechts commented on src/app.rs
> +            let mut kbd_signal = self.delete_dialog_state.keyboard_signal_select * 10;
thanks for that comment, I wanted to implement it like that but did the dirty version first and then forgot to change it...

2020-10-05 18:25 UTC, LlinksRechts commented
fixed the number input thing, and cleaned up my scroll list and merged it into this branch

2020-10-13 07:02 UTC, ClementTsang commented
Sorry, been busy for the past few days.  Let me know whenever you're ready for me to take another look and I'll check it + test it (just not sure about the status of this PR).  If it's good I'll merge.

2020-10-13 08:25 UTC, LlinksRechts commented
No problem! I've fixed the things you suggested and just rebased to master, so imo the PR should be good to go whenever you're happy with it also :)

2020-10-17 21:45 UTC, ClementTsang requested changes
Sorry for taking so long to do this.  Work ramping up and a bad sleep schedule haven't been kind to me.

---

I prefer the list approach a lot more, and it generally looks better and feels more responsive to resizes, so that's good.  However, a list approach brings in a lot of gotchas, mainly with how to achieve the list scrolling behaviour currently used in the application for other widgets.  I've left some tips on how to fix it, but I know it's currently a bit of a confusing mess so let me know if you need some more help on it.

I tested running it on macOS, it looks fine, though you should double check which signals are valid on macOS, because some signals are not accepted that do work on Linux.  Check htop and/or documentation for which signals are valid on macOS and Linux.

It looks fine on Windows as well other than the minor reversed movement bug, and you should make sure there aren't any warnings on compilation if you're using `cfg` to gate some of the imports:

![image](https://user-images.githubusercontent.com/34804052/96354033-d5ef3400-109f-11eb-9567-ccf4d93df12e.png)

I would also appreciate adding support for `G` and `gg` keybinds to jump to the end and start of the list respectively, but that's pretty easy for me to add later so no worries if it's not done in this PR.

2020-10-17 21:45 UTC, ClementTsang commented on src/canvas/dialogs/dd_dialog.rs
> +        );
This method doesn't really seem to work that well if you scroll past the first row and do clicking:

![Peek 2020-10-17 17-07](https://user-images.githubusercontent.com/34804052/96353560-3b8cf180-109b-11eb-959e-42e779b4886a.gif)

While it *does* select the correct entry, the list jumps around and it looks strange.  In comparison, try clicking on an entry in, say, the temperature list or the processes list.  The list should not shift when you click on an entry.

Look at something like `temp_table.rs` at line 51 on how I currently calculate the scroll offset:

```rs
let start_position = get_start_position(
    usize::from(
        (draw_loc.height + (1 - table_gap)).saturating_sub(self.table_height_offset),
    ),
    &temp_widget_state.scroll_state.scroll_direction,
    &mut temp_widget_state.scroll_state.previous_scroll_position,
    temp_widget_state.scroll_state.current_scroll_position,
    app_state.is_force_redraw,
);
//...
let sliced_vec = &temp_sensor_data[start_position..]; // This is properly offset.
```

The gist of it is that I already have a function that manages the calculation of where to start drawing the a scrollable list, and it requires storing some additional fields in the struct to do so.  I would have preferred to make this more intuitive to add, but I don't really have the time to do that right now unfortunately (I was planning on doing it later).  If this is a bit too confusing please let me know, I can try to help a bit more.

2020-10-17 21:45 UTC, ClementTsang commented on src/canvas/dialogs/dd_dialog.rs
> +            "64: RTMAX",
Does this list of signals hold for macOS?  I tried using 64 and it didn't work, for example.

2020-10-17 21:45 UTC, ClementTsang commented on src/app.rs
> +            };
On Windows this is broken, the movement is reversed.  Moving left moves right instead.

2020-10-24 18:23 UTC, LlinksRechts commented
since I haven't answered in a while: I haven't forgotten about this, and will look into the things you noted, but have a lot of other stuff currently, so I'll see when I have the time :)

2020-10-25 05:44 UTC, ClementTsang commented
No worries, I've also been a bit busy with IRL stuff too so I'm in no rush.

2020-12-07 09:18 UTC, LlinksRechts commented
Finally got around to looking into the things you commented; got some very good points there, thanks for the feedback!  
I changed the things you suggested; youre right, the list flows much more naturally now, and I really didn't think about different signals on MacOS :p Also, I added support for gg/G.  
If you could find some spare time to test this on windows once again that'd be great!

2020-12-16 01:35 UTC, ClementTsang commented
Took a look on macOS and Windows, looks good there.

I'll take a look at the code and if it looks good I'll merge.

2020-12-16 02:37 UTC, ClementTsang commented
@LlinksRechts LGTM.  I'll merge this - thanks for the work you've done!

@all-contributors add @LlinksRechts for code

2020-12-16 02:39 UTC, merged